// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGTavernBarmanBot.Data;

#nullable disable

namespace RPGTavernBarmanBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220417184353_RPGDataBase")]
    partial class RPGDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RPGTavernBarmanBot.Models.Game", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("GameColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameMaster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerDiscordId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("RPGTavernBarmanBot.Models.Players", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
